apiVersion: bundle.gravitational.io/v2
kind: SystemApplication
metadata:
  name: ingress-app
  resourceVersion: "0.0.1"
hooks:
  install:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: ingress-app-install
      spec:
        template:
          metadata:
            name: ingress-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:stretch
                command: ["/bin/sh", "/var/lib/gravity/resources/install.sh"]
  update:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: ingress-app-update
      spec:
        template:
          metadata:
            name: ingress-app-update
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:stretch
                command: ["/bin/sh", "/var/lib/gravity/resources/update.sh"]
  uninstall:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: ingress-app-uninstall
      spec:
        template:
          metadata:
            name: ingress-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:stretch
                command: ["/bin/sh", "/var/lib/gravity/resources/uninstall.sh"]
